language: generic

deploy:
  provider: s3
  access_key_id:
    secure: "qsKz4mpnUuYdZfmAXejQD0RSCgJm6YvxY4rmXoG4bJfMhvXE0AJyHcv0pUlZonbmDCryEDD8dtP8XvZw1eW8r/3lS3MO+jRPMDylxrqFHGSllZ6TQ7PblDuvLijyT+anXG8ok09xxasC1lzaTvmL+sfFraUmEhKC3R4HM6Iijv2vNBBhZDxhsYLmceWs0pTxLhRfa9Oo54nBrca9itSC06IfR8lGCF7lbWafFjnL+5neTXOF5z64KBXy0scwv7HE4E2CF8DxIAnku8Z/RbTdWho4h0O7UXhzIs5UgvYebr91CPXn91Bbk5fDcDXWy5/HO28XGxY21L83RS32wWdmVesTaAVfiadiS40wyqY4b1u1eFGfFj6A9EzIWhN0dpIyTwfWUfFV4ISk5W8Zqcv2yBi68lMKF1rwmISRNjdTpoTqggZ2RaLpfpgPyCOEtZmTiXppzTbVvvlO/l1gII4m8zWFMYUsP8C868M4jQKLXuVXqp54COybSkZ+MBqTI0s3A9qrnfAMrMoQvIHrM/JrtnzmmkKi5pLSw3Yy5BRshNs0PqBmsQsptawgR9g58pcQUgGBVkT7cAm35A0Gc8HBadzdoPVIIM9kK/H1OxQ0P0lHJrLj7lSLjxh8UTC+agR7Y8+G6yooYXunbR7CujLlho23qGMs/L/3a0ZCiTBLywc="
  secret_access_key:
    secure: "K5/NnWXmRzxrJuXpLVOekZJLMx/DaqwFPbCP68r346EZ+puq8Oh0jk6CB8OqRYehbWsKG9SfkdSz3JEsB55yqJYidP2+Lt62Gc73E1wkv7pBkUzJ4aXwe7fG3xDbsiPQrjUb5iwrPB3GSPD+9t9SPl3tj6ry+qTiN4206DCGaDpTGPRStUXjV8dVOP6FD2SEIW7yegsxJsJXCUX2dyJAxx4CQm8CNp85Rdwk9akyVGfiV9QT0MMAJMKTewa4Hi/QWyWQJ+i9o3cK8lRpt3jKEdyrpBTQAzpiiZRR9L5hylmiG6UUpUtNsTjgCpD3LU63kjMiIRnUz3Kkg+BUQHn1NSRGi+p3gHYqv8J8fkNrgZ4F27WL5pXwylJVm/vLTosixwbpJ4UOpe6uMuKdV40wnWV5c9CslRtLiUI4EquKX63u9C3Fuig7VbhkaHHZNMaVRmBwb9kbAL6GFUVfIvzjh1xQQE+Hyi36ydS58mPsFzfgFdAQxGo1HBdmrEfWIwhzFmaKeEuvAHSQzI7AXlYSxPoLcXBTuE6bi1AU759IwCFAXWKCwtdf14ghJZXTcjlksubadk1C4tOhDJ95XMNCpUrPQPypVmn5AgAKqxf92n5rCpiLX2k/XDUZarbJhMWAU9yPqeym4Eu9Mdpm3uO6GLW6VKysOay/gG8TyRtN+nU="
  bucket: andrewmacheret.com
  skip_cleanup: true
  acl: public_read
  region: us-east-1
  default_text_charset: utf-8
  detect_encoding: true
  local_dir: www
  upload_dir: projects/sprite-sandbox
